### ISSUE TITLE
/weathermap/editor.php is blank

### ISSUE THREAD

**Issue by danf22** [akender/weathermap-for-observium#1]
when I try to edit in /weathermap/editor.php the page is blank

**Comment by akender** [comment]
Thank you for notifying me.

1. Edit the /opt/observium/html/weathermap/editor-config.php file and make sure that observiumbase have right value (i.e http://localhost/).
2. Change "require_once 'lib/editor.inc_test.php';" to "require_once 'lib/editor.inc.php';" in editor.php file.

I made the changes in git.
